--
-- PostgreSQL database dump
--

\restrict d8LsZFrBVEf68g6IpawK7a8cQ2Y9ckaEr2w56HmUqI7x9DKeF8jGAfR9KbsU2c9

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-09-24 10:55:01 -03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16399)
-- Name: Administradores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Administradores" (
    "Id" integer NOT NULL,
    "Email" character varying(255) NOT NULL,
    "Senha" character varying(50) NOT NULL,
    "Perfil" character varying(10) NOT NULL
);


ALTER TABLE public."Administradores" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16398)
-- Name: Administradores_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Administradores" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Administradores_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16405)
-- Name: Veiculos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Veiculos" (
    "Id" integer NOT NULL,
    "Nome" character varying(150) NOT NULL,
    "Modelo" character varying(100) NOT NULL,
    "Ano" integer NOT NULL
);


ALTER TABLE public."Veiculos" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16404)
-- Name: Veiculos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Veiculos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Veiculos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16393)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4437 (class 0 OID 16399)
-- Dependencies: 219
-- Data for Name: Administradores; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Administradores" ("Id", "Email", "Senha", "Perfil") FROM stdin;
1	adm@teste.com	123456	Adm
2	eduardoamaral@teste.com	654321	Editor
\.


--
-- TOC entry 4439 (class 0 OID 16405)
-- Dependencies: 221
-- Data for Name: Veiculos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Veiculos" ("Id", "Nome", "Modelo", "Ano") FROM stdin;
1	Honda	City Touring II	2022
\.


--
-- TOC entry 4435 (class 0 OID 16393)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250921184210_AdministradorMigration	9.0.9
20250921190234_SeedAdministrador	9.0.9
20250921190401_SeedAdministradorII	9.0.9
20250921223737_VeiculoMigrations	9.0.9
\.


--
-- TOC entry 4445 (class 0 OID 0)
-- Dependencies: 218
-- Name: Administradores_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Administradores_Id_seq"', 3, true);


--
-- TOC entry 4446 (class 0 OID 0)
-- Dependencies: 220
-- Name: Veiculos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Veiculos_Id_seq"', 3, true);


--
-- TOC entry 4287 (class 2606 OID 16403)
-- Name: Administradores PK_Administradores; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Administradores"
    ADD CONSTRAINT "PK_Administradores" PRIMARY KEY ("Id");


--
-- TOC entry 4289 (class 2606 OID 16409)
-- Name: Veiculos PK_Veiculos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Veiculos"
    ADD CONSTRAINT "PK_Veiculos" PRIMARY KEY ("Id");


--
-- TOC entry 4285 (class 2606 OID 16397)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


-- Completed on 2025-09-24 10:55:02 -03

--
-- PostgreSQL database dump complete
--

\unrestrict d8LsZFrBVEf68g6IpawK7a8cQ2Y9ckaEr2w56HmUqI7x9DKeF8jGAfR9KbsU2c9

